{
 "title": "Aggregation Observing",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB_stc_dev", "query": "stc_dev" },
   { "name": "DB_stc_cdr_data", "query": "stc_cdr_data" }
  ]
 },
 "panels": [
  {
   "title": "Aggregation Threshold Reached",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "Select \n\tstartTime as time,\n\tNotification, \n\tcdr_voice_details_daily as TableName\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=DATE_SUB(NOW(),INTERVAL 1 DAY) THEN 1 ELSE 0 END AS Notification,\n'stc_cdr_data','cdr_voice_details_daily'\n,(select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_daily`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime \n FROM \n`stc_cdr_data`.`cdr_voice_details_daily`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data1\nwhere data1.Notification = 0 and $__timeFilter(data1.startTime)\n\nunion all\nSelect \n\tstartTime as time,\n\tNotification, \n\tcdr_voice_details_hourly as TableName\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=DATE_SUB(NOW(), INTERVAL 1 HOUR) THEN 1 ELSE 0 END AS Notification,'stc_cdr_data','cdr_voice_details_hourly'\n,(select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_hourly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\n FROM `stc_cdr_data`.`cdr_voice_details_hourly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data2\nwhere data2.Notification = 0 and $__timeFilter(data2.startTime)\n\nunion all\n\nSelect \n\tstartTime as time,\n\tNotification, \n\tcdr_voice_details_monthly as TableName\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=DATE_FORMAT(NOW() - INTERVAL 1 MONTH, '%Y/%m/01') THEN 1 ELSE 0 END AS Notification,'stc_cdr_data','cdr_voice_details_monthly'\n,(select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_monthly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\n FROM `stc_cdr_data`.`cdr_voice_details_monthly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data3\nwhere data3.Notification = 0 and $__timeFilter(data3.startTime)\n\nunion all\n\nSelect \n\tstartTime as time,\n\tNotification, \n\tcdr_voice_details_weekly as TableName\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=(DATE(NOW()) - INTERVAL 7 DAY) THEN 1 ELSE 0 END AS Notification,'stc_cdr_data','cdr_voice_details_weekly' \n,(select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_weekly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM `stc_cdr_data`.`cdr_voice_details_weekly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data4\nwhere data4.Notification = 0 and $__timeFilter(data4.startTime)\nunion all\n\nSelect \n\tstartTime as time,\n\tNotification, \n\tcdr_voice_details_yearly as TableName\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=YEAR(DATE_SUB(NOW(), INTERVAL 1 YEAR)) THEN 1 ELSE 0 \nEND AS Notification,'stc_cdr_data','cdr_voice_details_yearly'\n,(select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_yearly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM `stc_cdr_data`.`cdr_voice_details_yearly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data5\nwhere data5.Notification = 0 and $__timeFilter(data5.startTime)\n\nunion all\n\nSelect \n\tstartTime as time,\n\tNotification, \n\tcdr_data_details_daily as TableName\nfrom\n(SELECT CASE WHEN startTime>=DATE_SUB(NOW(),INTERVAL 1 DAY) THEN 1 ELSE 0 END AS Notification,'stc_cdr_data','cdr_data_details_daily'\n,(select startTime from `stc_cdr_data`.`cdr_data_details_daily`\nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM `stc_cdr_data`.`cdr_data_details_daily`  ORDER BY startTime DESC LIMIT 1 )\nas data11\nwhere data11.Notification = 0 and $__timeFilter(data11.startTime)\n\nunion all\n\nSelect \n\tsTime as time,\n\tNotification,\n\tcdr_data_details_hourly as TableName\nfrom\n(SELECT CASE WHEN startTime>=DATE_SUB(NOW(), INTERVAL 1 HOUR) THEN 1 ELSE 0 END AS Notification,'stc_cdr_data','cdr_data_details_hourly', \n(select startTime from `stc_cdr_data`.`cdr_data_details_hourly`\nORDER BY startTime DESC LIMIT 1 ) as sTime\nFROM `stc_cdr_data`.`cdr_data_details_hourly`  ORDER BY startTime DESC LIMIT 1 )\nas data12\nwhere data12.Notification = 0 and $__timeFilter(data12.sTime)\n\nunion all\n\nSelect \n\tstartTime as time,\n\tNotification, \n\tcdr_data_details_monthly as TableName\nfrom\n(SELECT CASE WHEN startTime>=DATE_FORMAT(NOW() - INTERVAL 1 MONTH, '%Y/%m/01') THEN 1 ELSE 0 END AS Notification,'stc_cdr_data','cdr_data_details_monthly'\n,(select startTime from `stc_cdr_data`.`cdr_data_details_monthly`\nORDER BY startTime DESC LIMIT 1 ) as startTime\n FROM `stc_cdr_data`.`cdr_data_details_monthly`  ORDER BY startTime DESC LIMIT 1 )\nas data13\nwhere data13.Notification = 0 and $__timeFilter(data13.startTime)\n\nunion all\n\nSelect \n\tstartTime as time,\n\tNotification, \n\tcdr_data_details_weekly as TableName\nfrom\n(SELECT CASE WHEN startTime>=(DATE(NOW()) - INTERVAL 7 DAY) THEN 1 ELSE 0 END AS Notification,'stc_cdr_data','cdr_data_details_weekly'\n,(select startTime from `stc_cdr_data`.`cdr_data_details_weekly`\nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM `stc_cdr_data`.`cdr_data_details_weekly`  ORDER BY startTime DESC LIMIT 1 )\nas data14\nwhere data14.Notification = 0 and $__timeFilter(data14.startTime)\n\nunion all\n\nSelect \n\tstartTime as time,\n\tNotification, \n\tcdr_data_details_yearly as TableName\nfrom\n(SELECT CASE WHEN startTime>=YEAR(DATE_SUB(NOW(), INTERVAL 1 YEAR)) THEN 1 ELSE 0 END AS Notification,'stc_cdr_data','cdr_data_details_yearly'\n,(select startTime from `stc_cdr_data`.`cdr_data_details_yearly`\nORDER BY startTime DESC LIMIT 1 ) as startTime\n FROM `stc_cdr_data`.`cdr_data_details_yearly`  ORDER BY startTime DESC LIMIT 1) \nas data15\nwhere data15.Notification = 0 and $__timeFilter(data15.startTime)\n\nunion all\n\nSelect \n\tstartTime as time, \n\tNotification, \n\tcdr_sms_details_daily as TableName    \nfrom\n(SELECT CASE WHEN FINAL_TIME>=DATE_SUB(NOW(),INTERVAL 1 DAY) THEN 1 ELSE 0 END AS Notification,\n'stc_cdr_data','cdr_sms_details_daily'\n,(select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_daily`\nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n FROM \n`stc_cdr_data`.`cdr_sms_details_daily`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data6\nwhere data6.Notification = 0 and $__timeFilter(data6.startTime)\n\nunion all\n\nSelect \n\tsTime as time, \n\tNotification,\n\tcdr_sms_details_hourly as TableName\nfrom\n(SELECT CASE WHEN FINAL_TIME>=DATE_SUB(NOW(), INTERVAL 1 HOUR) THEN 1 ELSE 0 END AS Notification,\n'stc_cdr_data','cdr_sms_details_hourly' \n,(select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_hourly`\nORDER BY FINAL_TIME DESC LIMIT 1 ) as sTime\nFROM `stc_cdr_data`.`cdr_sms_details_hourly`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data7\nwhere data7.Notification = 0 and $__timeFilter(data7.sTime)\n\nunion all\n\nSelect \n\tsTime as time, \n\tNotification,\n\tcdr_sms_details_monthly as TableName  \nfrom\n(SELECT CASE WHEN FINAL_TIME>=DATE_FORMAT(NOW() - INTERVAL 1 MONTH, '%Y/%m/01') THEN 1 ELSE 0 END AS Notification,\n'stc_cdr_data','cdr_sms_details_monthly' \n,(select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_monthly`\nORDER BY FINAL_TIME DESC LIMIT 1 ) as sTime\nFROM `stc_cdr_data`.cdr_sms_details_monthly  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data8\nwhere data8.Notification = 0 and $__timeFilter(data8.sTime)\n\nunion all\n\nSelect\n\tsTime as time, \n\tNotification, \n\tcdr_sms_details_weekly as TableName   \nfrom\n(SELECT CASE WHEN FINAL_TIME>=(DATE(NOW()) - INTERVAL 7 DAY) THEN 1 ELSE 0 END AS Notification,\n'stc_cdr_data','cdr_sms_details_weekly',FINAL_TIME \n,(select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_weekly`\nORDER BY FINAL_TIME ASC LIMIT 1 ) as sTime\nFROM `stc_cdr_data`.`cdr_sms_details_weekly`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data9\nwhere data9.Notification = 0 and $__timeFilter(data9.sTime)\n\nunion all\n\nSelect\n\tsTime as time, \n\tNotification, \n\tcdr_sms_details_yearly as TableName   \nfrom\n(SELECT CASE WHEN FINAL_TIME>=YEAR(DATE_SUB(NOW(), INTERVAL 1 YEAR)) THEN 1 ELSE 0 END AS Notification,'stc_cdr_data','cdr_sms_details_yearly'\n,(select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_yearly`\nORDER BY FINAL_TIME ASC LIMIT 1 ) as sTime\nFROM `stc_cdr_data`.`cdr_sms_details_yearly`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data10\nwhere data10.Notification = 0 and $__timeFilter(data10.sTime) ;"
    }
   ]
  },
  {
   "title": "Aggregation Threshold Data",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "Select \n\tcdr_voice_details_daily as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  startTime as time\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=DATE_SUB(NOW(),INTERVAL 1 DAY) THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_voice_details_daily'\n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_daily`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime \n FROM \n`$DB_stc_cdr_data`.`cdr_voice_details_daily`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data1\nwhere data1.Notification = 0 and $__timeFilter(data1.startTime)\n\nunion all\nSelect \n\tcdr_voice_details_hourly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  startTime as time\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=DATE_SUB(NOW(), INTERVAL 1 HOUR) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_voice_details_hourly'\n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_hourly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\n FROM `$DB_stc_cdr_data`.`cdr_voice_details_hourly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data2\nwhere data2.Notification = 0 and $__timeFilter(data2.startTime)\n\nunion all\n\nSelect \n\tcdr_voice_details_monthly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  startTime as time\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=DATE_FORMAT(NOW() - INTERVAL 1 MONTH, '%Y/%m/01') THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_voice_details_monthly'\n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_monthly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\n FROM `$DB_stc_cdr_data`.`cdr_voice_details_monthly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data3\nwhere data3.Notification = 0 and $__timeFilter(data3.startTime)\n\nunion all\n\nSelect \n\tcdr_voice_details_weekly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  startTime as time\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=(DATE(NOW()) - INTERVAL 7 DAY) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_voice_details_weekly' \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_weekly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM `$DB_stc_cdr_data`.`cdr_voice_details_weekly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data4\nwhere data4.Notification = 0 and $__timeFilter(data4.startTime)\nunion all\n\nSelect \n\tcdr_voice_details_yearly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  startTime as time\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=YEAR(DATE_SUB(NOW(), INTERVAL 1 YEAR)) THEN 1 ELSE 0 \nEND AS Notification,'$DB_stc_cdr_data' as data,'cdr_voice_details_yearly'\n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_yearly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM `$DB_stc_cdr_data`.`cdr_voice_details_yearly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data5\nwhere data5.Notification = 0 and $__timeFilter(data5.startTime)\n\nunion all\n\nSelect \n\tcdr_data_details_daily as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN startTime>=DATE_SUB(NOW(),INTERVAL 1 DAY) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_daily'\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_daily`\nORDER BY startTime DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_data_details_daily`  ORDER BY startTime DESC LIMIT 1 )\nas data11\nwhere data11.Notification = 0 and $__timeFilter(data11.sTime)\n\nunion all\n\nSelect \n\tcdr_data_details_hourly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN startTime>=DATE_SUB(NOW(), INTERVAL 1 HOUR) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_hourly', \n(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_hourly`\nORDER BY startTime DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_data_details_hourly`  ORDER BY startTime DESC LIMIT 1 )\nas data12\nwhere data12.Notification = 0 and $__timeFilter(data12.sTime)\n\nunion all\n\nSelect \n\tcdr_data_details_monthly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN startTime>=DATE_FORMAT(NOW() - INTERVAL 1 MONTH, '%Y/%m/01') THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_monthly'\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_monthly`\nORDER BY startTime DESC LIMIT 1 ) as sTime\n FROM `$DB_stc_cdr_data`.`cdr_data_details_monthly`  ORDER BY startTime DESC LIMIT 1 )\nas data13\nwhere data13.Notification = 0 and $__timeFilter(data13.sTime)\n\nunion all\n\nSelect \n\tcdr_data_details_weekly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN startTime>=(DATE(NOW()) - INTERVAL 7 DAY) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_weekly'\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_weekly`\nORDER BY startTime DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_data_details_weekly`  ORDER BY startTime DESC LIMIT 1 )\nas data14\nwhere data14.Notification = 0 and $__timeFilter(data14.sTime)\n\nunion all\n\nSelect \n\tcdr_data_details_yearly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN startTime>=YEAR(DATE_SUB(NOW(), INTERVAL 1 YEAR)) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_yearly'\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_yearly`\nORDER BY startTime DESC LIMIT 1 ) as sTime\n FROM `$DB_stc_cdr_data`.`cdr_data_details_yearly`  ORDER BY startTime DESC LIMIT 1) \nas data15\nwhere data15.Notification = 0 and $__timeFilter(data15.sTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_daily as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  startTime as time\nfrom\n(SELECT CASE WHEN FINAL_TIME>=DATE_SUB(NOW(),INTERVAL 1 DAY) THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_sms_details_daily'\n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_daily`\nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n FROM \n`$DB_stc_cdr_data`.`cdr_sms_details_daily`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data6\nwhere data6.Notification = 0 and $__timeFilter(data6.startTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_hourly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN FINAL_TIME>=DATE_SUB(NOW(), INTERVAL 1 HOUR) THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_sms_details_hourly' \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_hourly`\nORDER BY FINAL_TIME DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_sms_details_hourly`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data7\nwhere data7.Notification = 0 and $__timeFilter(data7.sTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_monthly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN FINAL_TIME>=DATE_FORMAT(NOW() - INTERVAL 1 MONTH, '%Y/%m/01') THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_sms_details_monthly' \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_monthly`\nORDER BY FINAL_TIME DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.cdr_sms_details_monthly  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data8\nwhere data8.Notification = 0 and $__timeFilter(data8.sTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_weekly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n    sTime as time\nfrom\n(SELECT CASE WHEN FINAL_TIME>=(DATE(NOW()) - INTERVAL 7 DAY) THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_sms_details_weekly',FINAL_TIME \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_weekly`\nORDER BY FINAL_TIME ASC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_sms_details_weekly`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data9\nwhere data9.Notification = 0 and $__timeFilter(data9.sTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_yearly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN FINAL_TIME>=YEAR(DATE_SUB(NOW(), INTERVAL 1 YEAR)) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_sms_details_yearly'\n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_yearly`\nORDER BY FINAL_TIME ASC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_sms_details_yearly`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data10\nwhere data10.Notification = 0 and $__timeFilter(data10.sTime) ;"
    }
   ]
  },
  {
   "title": "Aggregation Threshold Not Reached Data",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "Select \n\tcdr_voice_details_daily as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  startTime as time\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=DATE_SUB(NOW(),INTERVAL 1 DAY) THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_voice_details_daily'\n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_daily`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime \n FROM \n`$DB_stc_cdr_data`.`cdr_voice_details_daily`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data1\nwhere data1.Notification = 1 and $__timeFilter(data1.startTime)\n\nunion all\nSelect \n\tcdr_voice_details_hourly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  startTime as time\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=DATE_SUB(NOW(), INTERVAL 1 HOUR) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_voice_details_hourly'\n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_hourly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\n FROM `$DB_stc_cdr_data`.`cdr_voice_details_hourly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data2\nwhere data2.Notification = 1 and $__timeFilter(data2.startTime)\n\nunion all\n\nSelect \n\tcdr_voice_details_monthly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  startTime as time\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=DATE_FORMAT(NOW() - INTERVAL 1 MONTH, '%Y/%m/01') THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_voice_details_monthly'\n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_monthly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\n FROM `$DB_stc_cdr_data`.`cdr_voice_details_monthly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data3\nwhere data3.Notification = 1 and $__timeFilter(data3.startTime)\n\nunion all\n\nSelect \n\tcdr_voice_details_weekly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  startTime as time\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=(DATE(NOW()) - INTERVAL 7 DAY) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_voice_details_weekly' \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_weekly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM `$DB_stc_cdr_data`.`cdr_voice_details_weekly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data4\nwhere data4.Notification = 1 and $__timeFilter(data4.startTime)\nunion all\n\nSelect \n\tcdr_voice_details_yearly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  startTime as time\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=YEAR(DATE_SUB(NOW(), INTERVAL 1 YEAR)) THEN 1 ELSE 0 \nEND AS Notification,'$DB_stc_cdr_data' as data,'cdr_voice_details_yearly'\n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_yearly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM `$DB_stc_cdr_data`.`cdr_voice_details_yearly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data5\nwhere data5.Notification = 1 and $__timeFilter(data5.startTime)\n\nunion all\n\nSelect \n\tcdr_data_details_daily as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN startTime>=DATE_SUB(NOW(),INTERVAL 1 DAY) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_daily'\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_daily`\nORDER BY startTime DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_data_details_daily`  ORDER BY startTime DESC LIMIT 1 )\nas data11\nwhere data11.Notification = 1 and $__timeFilter(data11.sTime)\n\nunion all\n\nSelect \n\tcdr_data_details_hourly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN startTime>=DATE_SUB(NOW(), INTERVAL 1 HOUR) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_hourly', \n(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_hourly`\nORDER BY startTime DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_data_details_hourly`  ORDER BY startTime DESC LIMIT 1 )\nas data12\nwhere data12.Notification = 1 and $__timeFilter(data12.sTime)\n\nunion all\n\nSelect \n\tcdr_data_details_monthly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN startTime>=DATE_FORMAT(NOW() - INTERVAL 1 MONTH, '%Y/%m/01') THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_monthly'\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_monthly`\nORDER BY startTime DESC LIMIT 1 ) as sTime\n FROM `$DB_stc_cdr_data`.`cdr_data_details_monthly`  ORDER BY startTime DESC LIMIT 1 )\nas data13\nwhere data13.Notification = 1 and $__timeFilter(data13.sTime)\n\nunion all\n\nSelect \n\tcdr_data_details_weekly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN startTime>=(DATE(NOW()) - INTERVAL 7 DAY) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_weekly'\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_weekly`\nORDER BY startTime DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_data_details_weekly`  ORDER BY startTime DESC LIMIT 1 )\nas data14\nwhere data14.Notification = 1 and $__timeFilter(data14.sTime)\n\nunion all\n\nSelect \n\tcdr_data_details_yearly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN startTime>=YEAR(DATE_SUB(NOW(), INTERVAL 1 YEAR)) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_yearly'\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_yearly`\nORDER BY startTime DESC LIMIT 1 ) as sTime\n FROM `$DB_stc_cdr_data`.`cdr_data_details_yearly`  ORDER BY startTime DESC LIMIT 1) \nas data15\nwhere data15.Notification = 1 and $__timeFilter(data15.sTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_daily as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  startTime as time\nfrom\n(SELECT CASE WHEN FINAL_TIME>=DATE_SUB(NOW(),INTERVAL 1 DAY) THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_sms_details_daily'\n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_daily`\nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n FROM \n`$DB_stc_cdr_data`.`cdr_sms_details_daily`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data6\nwhere data6.Notification = 1 and $__timeFilter(data6.startTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_hourly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN FINAL_TIME>=DATE_SUB(NOW(), INTERVAL 1 HOUR) THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_sms_details_hourly' \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_hourly`\nORDER BY FINAL_TIME DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_sms_details_hourly`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data7\nwhere data7.Notification = 1 and $__timeFilter(data7.sTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_monthly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN FINAL_TIME>=DATE_FORMAT(NOW() - INTERVAL 1 MONTH, '%Y/%m/01') THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_sms_details_monthly' \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_monthly`\nORDER BY FINAL_TIME DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.cdr_sms_details_monthly  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data8\nwhere data8.Notification = 1 and $__timeFilter(data8.sTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_weekly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n    sTime as time\nfrom\n(SELECT CASE WHEN FINAL_TIME>=(DATE(NOW()) - INTERVAL 7 DAY) THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_sms_details_weekly',FINAL_TIME \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_weekly`\nORDER BY FINAL_TIME ASC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_sms_details_weekly`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data9\nwhere data9.Notification = 1 and $__timeFilter(data9.sTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_yearly as TableName,\n\tdata as DatabaseName,\n\tNotification,\n  sTime as time\nfrom\n(SELECT CASE WHEN FINAL_TIME>=YEAR(DATE_SUB(NOW(), INTERVAL 1 YEAR)) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_sms_details_yearly'\n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_yearly`\nORDER BY FINAL_TIME ASC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_sms_details_yearly`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data10\nwhere data10.Notification = 1 and $__timeFilter(data10.sTime) ;"
    }
   ]
  },
  {
   "title": "Aggregation Threshold Not Reached",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "Select \n\tcdr_voice_details_daily as TableName,\n\tNotification\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=DATE_SUB(NOW(),INTERVAL 1 DAY) THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_voice_details_daily'\n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_daily`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime \n FROM \n`$DB_stc_cdr_data`.`cdr_voice_details_daily`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data1\nwhere data1.Notification = 1 and $__timeFilter(data1.startTime)\n\nunion all\nSelect \n\tcdr_voice_details_hourly as TableName,\n\tNotification\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=DATE_SUB(NOW(), INTERVAL 1 HOUR) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_voice_details_hourly'\n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_hourly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\n FROM `$DB_stc_cdr_data`.`cdr_voice_details_hourly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data2\nwhere data2.Notification = 1 and $__timeFilter(data2.startTime)\n\nunion all\n\nSelect \n\tcdr_voice_details_monthly as TableName,\n\tNotification\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=DATE_FORMAT(NOW() - INTERVAL 1 MONTH, '%Y/%m/01') THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_voice_details_monthly'\n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_monthly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\n FROM `$DB_stc_cdr_data`.`cdr_voice_details_monthly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data3\nwhere data3.Notification = 1 and $__timeFilter(data3.startTime)\n\nunion all\n\nSelect \n\tcdr_voice_details_weekly as TableName,\n\tNotification\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=(DATE(NOW()) - INTERVAL 7 DAY) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_voice_details_weekly' \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_weekly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM `$DB_stc_cdr_data`.`cdr_voice_details_weekly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data4\nwhere data4.Notification = 1 and $__timeFilter(data4.startTime)\nunion all\n\nSelect \n\tcdr_voice_details_yearly as TableName,\n\tNotification\nfrom\n(SELECT CASE WHEN ANSWERING_TIME>=YEAR(DATE_SUB(NOW(), INTERVAL 1 YEAR)) THEN 1 ELSE 0 \nEND AS Notification,'$DB_stc_cdr_data' as data,'cdr_voice_details_yearly'\n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_yearly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM `$DB_stc_cdr_data`.`cdr_voice_details_yearly`  ORDER BY ANSWERING_TIME DESC LIMIT 1 )\nas data5\nwhere data5.Notification = 1 and $__timeFilter(data5.startTime)\n\nunion all\n\nSelect \n\tcdr_data_details_daily as TableName,\n\tNotification\nfrom\n(SELECT CASE WHEN startTime>=DATE_SUB(NOW(),INTERVAL 1 DAY) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_daily'\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_daily`\nORDER BY startTime DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_data_details_daily`  ORDER BY startTime DESC LIMIT 1 )\nas data11\nwhere data11.Notification = 1 and $__timeFilter(data11.sTime)\n\nunion all\n\nSelect \n\tcdr_data_details_hourly as TableName,\n\tNotification\nfrom\n(SELECT CASE WHEN startTime>=DATE_SUB(NOW(), INTERVAL 1 HOUR) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_hourly', \n(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_hourly`\nORDER BY startTime DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_data_details_hourly`  ORDER BY startTime DESC LIMIT 1 )\nas data12\nwhere data12.Notification = 1 and $__timeFilter(data12.sTime)\n\nunion all\n\nSelect \n\tcdr_data_details_monthly as TableName,\n\tNotification\nfrom\n(SELECT CASE WHEN startTime>=DATE_FORMAT(NOW() - INTERVAL 1 MONTH, '%Y/%m/01') THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_monthly'\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_monthly`\nORDER BY startTime DESC LIMIT 1 ) as sTime\n FROM `$DB_stc_cdr_data`.`cdr_data_details_monthly`  ORDER BY startTime DESC LIMIT 1 )\nas data13\nwhere data13.Notification = 1 and $__timeFilter(data13.sTime)\n\nunion all\n\nSelect \n\tcdr_data_details_weekly as TableName,\t\n\tNotification\nfrom\n(SELECT CASE WHEN startTime>=(DATE(NOW()) - INTERVAL 7 DAY) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_weekly'\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_weekly`\nORDER BY startTime DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_data_details_weekly`  ORDER BY startTime DESC LIMIT 1 )\nas data14\nwhere data14.Notification = 1 and $__timeFilter(data14.sTime)\n\nunion all\n\nSelect \n\tcdr_data_details_yearly as TableName,\n\tNotification\nfrom\n(SELECT CASE WHEN startTime>=YEAR(DATE_SUB(NOW(), INTERVAL 1 YEAR)) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_data_details_yearly'\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_yearly`\nORDER BY startTime DESC LIMIT 1 ) as sTime\n FROM `$DB_stc_cdr_data`.`cdr_data_details_yearly`  ORDER BY startTime DESC LIMIT 1) \nas data15\nwhere data15.Notification = 1 and $__timeFilter(data15.sTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_daily as TableName,\n\tNotification\nfrom\n(SELECT CASE WHEN FINAL_TIME>=DATE_SUB(NOW(),INTERVAL 1 DAY) THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_sms_details_daily'\n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_daily`\nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n FROM \n`$DB_stc_cdr_data`.`cdr_sms_details_daily`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data6\nwhere data6.Notification = 1 and $__timeFilter(data6.startTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_hourly as TableName,\n\tNotification\nfrom\n(SELECT CASE WHEN FINAL_TIME>=DATE_SUB(NOW(), INTERVAL 1 HOUR) THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_sms_details_hourly' \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_hourly`\nORDER BY FINAL_TIME DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_sms_details_hourly`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data7\nwhere data7.Notification = 1 and $__timeFilter(data7.sTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_monthly as TableName,\n\tNotification\nfrom\n(SELECT CASE WHEN FINAL_TIME>=DATE_FORMAT(NOW() - INTERVAL 1 MONTH, '%Y/%m/01') THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_sms_details_monthly' \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_monthly`\nORDER BY FINAL_TIME DESC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.cdr_sms_details_monthly  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data8\nwhere data8.Notification = 1 and $__timeFilter(data8.sTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_weekly as TableName,\n    Notification\nfrom\n(SELECT CASE WHEN FINAL_TIME>=(DATE(NOW()) - INTERVAL 7 DAY) THEN 1 ELSE 0 END AS Notification,\n'$DB_stc_cdr_data' as data,'cdr_sms_details_weekly',FINAL_TIME \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_weekly`\nORDER BY FINAL_TIME ASC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_sms_details_weekly`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data9\nwhere data9.Notification = 1 and $__timeFilter(data9.sTime)\n\nunion all\n\nSelect \n\tcdr_sms_details_yearly as TableName,\n\tNotification\nfrom\n(SELECT CASE WHEN FINAL_TIME>=YEAR(DATE_SUB(NOW(), INTERVAL 1 YEAR)) THEN 1 ELSE 0 END AS Notification,'$DB_stc_cdr_data' as data,'cdr_sms_details_yearly'\n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_yearly`\nORDER BY FINAL_TIME ASC LIMIT 1 ) as sTime\nFROM `$DB_stc_cdr_data`.`cdr_sms_details_yearly`  ORDER BY FINAL_TIME DESC LIMIT 1 )\nas data10\nwhere data10.Notification = 1 and $__timeFilter(data10.sTime) ;"
    }
   ]
  }
 ]
}