{
 "title": "Partitioning Observing",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB_stc_dev", "query": "stc_dev" },
   { "name": "DB_stc_cdr_data", "query": "stc_cdr_data" }
  ]
 },
 "panels": [
  {
   "title": "Partitioning Threshold Reached",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "Select\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND TABLE_NAME='rule_engine_auditlog' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `stc_cdr_data`.`rule_engine_auditlog` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime \nFROM table_partition_policy WHERE table_name='rule_engine_auditlog' ORDER BY id DESC LIMIT 1 )\nas data1\nwhere data1.Notification=0 and data1.startTime IS Not Null\nand $__timeFilter(data1.startTime) \n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_data_details_daily' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `stc_cdr_data`.`cdr_data_details_daily` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_daily' ORDER BY id DESC LIMIT 1 )\nas data8\nwhere data8.Notification=0 and data8.startTime IS Not Null\nand $__timeFilter(data8.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName \nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_data_details_hourly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `stc_cdr_data`.`cdr_data_details_hourly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_hourly' ORDER BY id DESC LIMIT 1 )\nas data9\nwhere data9.Notification=0 and data9.startTime IS Not Null and $__timeFilter(data9.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_data_details_monthly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `stc_cdr_data`.`cdr_data_details_monthly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_monthly' ORDER BY id DESC LIMIT 1 )\nas data10\nwhere data10.Notification=0 and data10.startTime IS Not Null and $__timeFilter(data10.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_data_details_weekly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `stc_cdr_data`.`cdr_data_details_weekly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_data_details_weekly' ORDER BY id DESC LIMIT 1 )\nas data11\nwhere data11.Notification=0 and data11.startTime IS Not Null and $__timeFilter(data11.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < (YEAR(NOW())-IFNULL((select PARTITION_DESCRIPTION from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_data_details_yearly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `stc_cdr_data`.`cdr_data_details_yearly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_yearly' ORDER BY id DESC LIMIT 1 )\nas data12\nwhere data12.Notification=0 and data12.startTime IS Not Null and $__timeFilter(data12.startTime)\n\nunion all\n-- Select\n-- \tUNIX_TIMESTAMP(startTime) as time,\n-- \tNotification, \n-- \ttable_name as TableName\n-- from\n-- (SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA=`$DB_stc_cdr_data` AND  TABLE_NAME='cdr_sms_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n-- ,(select FINAL_TIME from cdr_database.cdr_sms_details \n-- ORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\n-- FROM table_partition_policy WHERE table_name='cdr_sms_details' ORDER BY id DESC LIMIT 1 )\n-- as data13\n-- where data13.Notification=1 and data13.startTime IS Not Null and $__timeFilter(data13.startTime)\n\n-- union all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_daily' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_daily` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_sms_details_daily' ORDER BY id DESC LIMIT 1 )\nas data14\nwhere data14.Notification=0 and data14.startTime IS Not Null and $__timeFilter(data14.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_hourly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_hourly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_sms_details_hourly' ORDER BY id DESC LIMIT 1 )\nas data15\nwhere data15.Notification=0 and data15.startTime IS Not Null and $__timeFilter(data15.startTime)\n\nunion all\n\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName  \nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_monthly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_monthly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details_monthly' ORDER BY id DESC LIMIT 1 )\nas data16\nwhere data16.Notification=0 and data16.startTime IS Not Null and $__timeFilter(data16.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_weekly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_weekly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details_weekly' ORDER BY id DESC LIMIT 1 )\nas data17\nwhere data17.Notification=0 and data17.startTime IS Not Null and $__timeFilter(data17.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName \nfrom\n(SELECT CASE WHEN in_no_of_partitions < (YEAR(NOW())-IFNULL((select PARTITION_DESCRIPTION from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_yearly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_yearly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details_yearly' ORDER BY id DESC LIMIT 1 )\nas data18\nwhere data18.Notification=0 and data18.startTime IS Not Null and $__timeFilter(data18.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName \nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_daily' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_daily`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_daily' ORDER BY id DESC LIMIT 1 )\nas data19\nwhere data19.Notification=0 and data19.startTime IS Not Null and $__timeFilter(data19.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_hourly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_hourly` \nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_hourly' ORDER BY id DESC LIMIT 1 )\nas data20\nwhere data20.Notification=0 and data20.startTime IS Not Null and $__timeFilter(data20.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_monthly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_monthly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_monthly' ORDER BY id DESC LIMIT 1 )\nas data21\nwhere data21.Notification=0 and data21.startTime IS Not Null and $__timeFilter(data21.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_weekly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_weekly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_weekly' ORDER BY id DESC LIMIT 1 )\nas data22\nwhere data22.Notification=0 and data22.startTime IS Not Null and $__timeFilter(data22.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < (YEAR(NOW())-IFNULL((select PARTITION_DESCRIPTION from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_yearly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_yearly` \nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_voice_details_yearly' ORDER BY id DESC LIMIT 1 )\nas data23\nwhere data23.Notification=0 and data23.startTime IS Not Null and $__timeFilter(data23.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName \nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_cdr_data' AND  TABLE_NAME='rule_engine_alert_history' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select occurence_time from `stc_cdr_data`.`rule_engine_alert_history` \nORDER BY occurence_time DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='rule_engine_alert_history' ORDER BY id DESC LIMIT 1 )\nas data24\nwhere data24.Notification=0 and data24.startTime IS Not Null and $__timeFilter(data24.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName \nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_dev' AND  TABLE_NAME='auditlog_end_points' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `stc_dev`.`auditlog_end_points` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='auditlog_end_points' ORDER BY id DESC LIMIT 1 )\nas data4\nwhere data4.Notification=0 and data4.startTime IS Not Null and $__timeFilter(data4.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from   INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_dev' AND  TABLE_NAME='auditlog' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `stc_dev`.`auditlog` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='auditlog' ORDER BY id DESC LIMIT 1 )\nas data2\nwhere data2.Notification=0 and data2.startTime IS Not Null and $__timeFilter(data2.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_dev' AND TABLE_NAME='auditlog_api_transaction' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `stc_dev`.`auditlog_api_transaction` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='auditlog_api_transaction' ORDER BY id DESC LIMIT 1 )\nas data3\nwhere data3.Notification=0 and data3.startTime IS Not Null and $__timeFilter(data3.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName \nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_SCHEMA='stc_dev' AND  TABLE_NAME='cdr_sms_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `stc_dev`.`cdr_sms_details` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details' ORDER BY id DESC LIMIT 1 )\nas data5\nwhere data5.Notification=0 and data5.startTime IS Not Null and $__timeFilter(data5.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_SCHEMA='stc_dev' AND  TABLE_NAME='cdr_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `stc_dev`.`cdr_details`  \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_details' ORDER BY id DESC LIMIT 1 )\nas data6\nwhere data6.Notification=0 and data6.startTime IS Not Null and $__timeFilter(data6.startTime)\n\nunion all\nSelect\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n\ttable_name as TableName\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='stc_dev' AND TABLE_NAME='cdr_voice_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `stc_dev`.`cdr_voice_details` \nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details' ORDER BY id DESC LIMIT 1 )\nas data7\nwhere data7.Notification=0 and data7.startTime IS Not Null and $__timeFilter(data7.startTime) ;\n"
    }
   ]
  },
  {
   "title": "Partitioning Threshold Reached Data",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "Select\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND TABLE_NAME='rule_engine_auditlog' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `$DB_stc_cdr_data`.`rule_engine_auditlog` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime \nFROM table_partition_policy WHERE table_name='rule_engine_auditlog' ORDER BY id DESC LIMIT 1 )\nas data1\nwhere data1.Notification=0 and data1.startTime IS Not Null\nand $__timeFilter(data1.startTime) \n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_daily' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_daily` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_daily' ORDER BY id DESC LIMIT 1 )\nas data8\nwhere data8.Notification=0 and data8.startTime IS Not Null\nand $__timeFilter(data8.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_hourly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_hourly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_hourly' ORDER BY id DESC LIMIT 1 )\nas data9\nwhere data9.Notification=0 and data9.startTime IS Not Null and $__timeFilter(data9.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_monthly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_monthly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_monthly' ORDER BY id DESC LIMIT 1 )\nas data10\nwhere data10.Notification=0 and data10.startTime IS Not Null and $__timeFilter(data10.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_weekly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_weekly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_data_details_weekly' ORDER BY id DESC LIMIT 1 )\nas data11\nwhere data11.Notification=0 and data11.startTime IS Not Null and $__timeFilter(data11.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < (YEAR(NOW())-IFNULL((select PARTITION_DESCRIPTION from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_yearly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_yearly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_yearly' ORDER BY id DESC LIMIT 1 )\nas data12\nwhere data12.Notification=0 and data12.startTime IS Not Null and $__timeFilter(data12.startTime)\n\nunion all\n-- Select\n-- \tUNIX_TIMESTAMP(startTime) as time,\n-- \tNotification, \n-- \ttable_name as TableName\n-- from\n-- (SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA=`$DB_stc_cdr_data` AND  TABLE_NAME='cdr_sms_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n-- ,(select FINAL_TIME from cdr_database.cdr_sms_details \n-- ORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\n-- FROM table_partition_policy WHERE table_name='cdr_sms_details' ORDER BY id DESC LIMIT 1 )\n-- as data13\n-- where data13.Notification=1 and data13.startTime IS Not Null and $__timeFilter(data13.startTime)\n\n-- union all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_daily' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_daily` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_sms_details_daily' ORDER BY id DESC LIMIT 1 )\nas data14\nwhere data14.Notification=0 and data14.startTime IS Not Null and $__timeFilter(data14.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_hourly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_hourly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_sms_details_hourly' ORDER BY id DESC LIMIT 1 )\nas data15\nwhere data15.Notification=0 and data15.startTime IS Not Null and $__timeFilter(data15.startTime)\n\nunion all\n\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_monthly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_monthly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details_monthly' ORDER BY id DESC LIMIT 1 )\nas data16\nwhere data16.Notification=0 and data16.startTime IS Not Null and $__timeFilter(data16.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_weekly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_weekly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details_weekly' ORDER BY id DESC LIMIT 1 )\nas data17\nwhere data17.Notification=0 and data17.startTime IS Not Null and $__timeFilter(data17.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < (YEAR(NOW())-IFNULL((select PARTITION_DESCRIPTION from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_yearly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_yearly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details_yearly' ORDER BY id DESC LIMIT 1 )\nas data18\nwhere data18.Notification=0 and data18.startTime IS Not Null and $__timeFilter(data18.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_daily' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_daily`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_daily' ORDER BY id DESC LIMIT 1 )\nas data19\nwhere data19.Notification=0 and data19.startTime IS Not Null and $__timeFilter(data19.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_hourly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_hourly` \nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_hourly' ORDER BY id DESC LIMIT 1 )\nas data20\nwhere data20.Notification=0 and data20.startTime IS Not Null and $__timeFilter(data20.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_monthly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_monthly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_monthly' ORDER BY id DESC LIMIT 1 )\nas data21\nwhere data21.Notification=0 and data21.startTime IS Not Null and $__timeFilter(data21.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_weekly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_weekly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_weekly' ORDER BY id DESC LIMIT 1 )\nas data22\nwhere data22.Notification=0 and data22.startTime IS Not Null and $__timeFilter(data22.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < (YEAR(NOW())-IFNULL((select PARTITION_DESCRIPTION from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_yearly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_yearly` \nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_voice_details_yearly' ORDER BY id DESC LIMIT 1 )\nas data23\nwhere data23.Notification=0 and data23.startTime IS Not Null and $__timeFilter(data23.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='rule_engine_alert_history' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select occurence_time from `$DB_stc_cdr_data`.`rule_engine_alert_history` \nORDER BY occurence_time DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='rule_engine_alert_history' ORDER BY id DESC LIMIT 1 )\nas data24\nwhere data24.Notification=0 and data24.startTime IS Not Null and $__timeFilter(data24.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_dev' AND  TABLE_NAME='auditlog_end_points' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `$DB_stc_dev`.`auditlog_end_points` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='auditlog_end_points' ORDER BY id DESC LIMIT 1 )\nas data4\nwhere data4.Notification=0 and data4.startTime IS Not Null and $__timeFilter(data4.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from   INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_dev' AND  TABLE_NAME='auditlog' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `$DB_stc_dev`.`auditlog` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='auditlog' ORDER BY id DESC LIMIT 1 )\nas data2\nwhere data2.Notification=0 and data2.startTime IS Not Null and $__timeFilter(data2.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_dev' AND TABLE_NAME='auditlog_api_transaction' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `$DB_stc_dev`.`auditlog_api_transaction` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='auditlog_api_transaction' ORDER BY id DESC LIMIT 1 )\nas data3\nwhere data3.Notification=0 and data3.startTime IS Not Null and $__timeFilter(data3.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_SCHEMA='$DB_stc_dev' AND  TABLE_NAME='cdr_sms_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_dev`.`cdr_sms_details` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details' ORDER BY id DESC LIMIT 1 )\nas data5\nwhere data5.Notification=0 and data5.startTime IS Not Null and $__timeFilter(data5.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_SCHEMA='$DB_stc_dev' AND  TABLE_NAME='cdr_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_dev`.`cdr_details`  \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_details' ORDER BY id DESC LIMIT 1 )\nas data6\nwhere data6.Notification=0 and data6.startTime IS Not Null and $__timeFilter(data6.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_dev' AND TABLE_NAME='cdr_voice_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_dev`.`cdr_voice_details` \nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details' ORDER BY id DESC LIMIT 1 )\nas data7\nwhere data7.Notification=0 and data7.startTime IS Not Null and $__timeFilter(data7.startTime) ;\n"
    }
   ]
  },
  {
   "title": "Partitioning Threshold not Reached",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "Select\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND TABLE_NAME='rule_engine_auditlog' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `$DB_stc_cdr_data`.`rule_engine_auditlog` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime \nFROM table_partition_policy WHERE table_name='rule_engine_auditlog' ORDER BY id DESC LIMIT 1 )\nas data1\nwhere data1.Notification=1 and data1.startTime IS Not Null\nand $__timeFilter(data1.startTime) \n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_daily' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_daily` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_daily' ORDER BY id DESC LIMIT 1 )\nas data8\nwhere data8.Notification=1 and data8.startTime IS Not Null\nand $__timeFilter(data8.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_hourly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_hourly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_hourly' ORDER BY id DESC LIMIT 1 )\nas data9\nwhere data9.Notification=1 and data9.startTime IS Not Null and $__timeFilter(data9.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_monthly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_monthly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_monthly' ORDER BY id DESC LIMIT 1 )\nas data10\nwhere data10.Notification=1 and data10.startTime IS Not Null and $__timeFilter(data10.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_weekly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_weekly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_data_details_weekly' ORDER BY id DESC LIMIT 1 )\nas data11\nwhere data11.Notification=1 and data11.startTime IS Not Null and $__timeFilter(data11.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < (YEAR(NOW())-IFNULL((select PARTITION_DESCRIPTION from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_yearly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_yearly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_yearly' ORDER BY id DESC LIMIT 1 )\nas data12\nwhere data12.Notification=1 and data12.startTime IS Not Null and $__timeFilter(data12.startTime)\n\nunion all\n-- Select\n-- \tUNIX_TIMESTAMP(startTime) as time,\n-- \tNotification, \n-- \ttable_name as TableName\n-- from\n-- (SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA=`$DB_stc_cdr_data` AND  TABLE_NAME='cdr_sms_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n-- ,(select FINAL_TIME from cdr_database.cdr_sms_details \n-- ORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\n-- FROM table_partition_policy WHERE table_name='cdr_sms_details' ORDER BY id DESC LIMIT 1 )\n-- as data13\n-- where data13.Notification=1 and data13.startTime IS Not Null and $__timeFilter(data13.startTime)\n\n-- union all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_daily' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_daily` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_sms_details_daily' ORDER BY id DESC LIMIT 1 )\nas data14\nwhere data14.Notification=1 and data14.startTime IS Not Null and $__timeFilter(data14.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_hourly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_hourly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_sms_details_hourly' ORDER BY id DESC LIMIT 1 )\nas data15\nwhere data15.Notification=1 and data15.startTime IS Not Null and $__timeFilter(data15.startTime)\n\nunion all\n\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_monthly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_monthly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details_monthly' ORDER BY id DESC LIMIT 1 )\nas data16\nwhere data16.Notification=1 and data16.startTime IS Not Null and $__timeFilter(data16.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_weekly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_weekly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details_weekly' ORDER BY id DESC LIMIT 1 )\nas data17\nwhere data17.Notification=1 and data17.startTime IS Not Null and $__timeFilter(data17.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < (YEAR(NOW())-IFNULL((select PARTITION_DESCRIPTION from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_yearly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_yearly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details_yearly' ORDER BY id DESC LIMIT 1 )\nas data18\nwhere data18.Notification=1 and data18.startTime IS Not Null and $__timeFilter(data18.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_daily' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_daily`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_daily' ORDER BY id DESC LIMIT 1 )\nas data19\nwhere data19.Notification=1 and data19.startTime IS Not Null and $__timeFilter(data19.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_hourly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_hourly` \nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_hourly' ORDER BY id DESC LIMIT 1 )\nas data20\nwhere data20.Notification=1 and data20.startTime IS Not Null and $__timeFilter(data20.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_monthly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_monthly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_monthly' ORDER BY id DESC LIMIT 1 )\nas data21\nwhere data21.Notification=1 and data21.startTime IS Not Null and $__timeFilter(data21.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_weekly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_weekly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_weekly' ORDER BY id DESC LIMIT 1 )\nas data22\nwhere data22.Notification=1 and data22.startTime IS Not Null and $__timeFilter(data22.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < (YEAR(NOW())-IFNULL((select PARTITION_DESCRIPTION from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_yearly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_yearly` \nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_voice_details_yearly' ORDER BY id DESC LIMIT 1 )\nas data23\nwhere data23.Notification=1 and data23.startTime IS Not Null and $__timeFilter(data23.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='rule_engine_alert_history' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select occurence_time from `$DB_stc_cdr_data`.`rule_engine_alert_history` \nORDER BY occurence_time DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='rule_engine_alert_history' ORDER BY id DESC LIMIT 1 )\nas data24\nwhere data24.Notification=1 and data24.startTime IS Not Null and $__timeFilter(data24.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_dev' AND  TABLE_NAME='auditlog_end_points' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `$DB_stc_dev`.`auditlog_end_points` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='auditlog_end_points' ORDER BY id DESC LIMIT 1 )\nas data4\nwhere data4.Notification=1 and data4.startTime IS Not Null and $__timeFilter(data4.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from   INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_dev' AND  TABLE_NAME='auditlog' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `$DB_stc_dev`.`auditlog` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='auditlog' ORDER BY id DESC LIMIT 1 )\nas data2\nwhere data2.Notification=1 and data2.startTime IS Not Null and $__timeFilter(data2.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_dev' AND TABLE_NAME='auditlog_api_transaction' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `$DB_stc_dev`.`auditlog_api_transaction` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='auditlog_api_transaction' ORDER BY id DESC LIMIT 1 )\nas data3\nwhere data3.Notification=1 and data3.startTime IS Not Null and $__timeFilter(data3.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_SCHEMA='$DB_stc_dev' AND  TABLE_NAME='cdr_sms_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_dev`.`cdr_sms_details` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details' ORDER BY id DESC LIMIT 1 )\nas data5\nwhere data5.Notification=1 and data5.startTime IS Not Null and $__timeFilter(data5.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_SCHEMA='$DB_stc_dev' AND  TABLE_NAME='cdr_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_dev`.`cdr_details`  \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_details' ORDER BY id DESC LIMIT 1 )\nas data6\nwhere data6.Notification=1 and data6.startTime IS Not Null and $__timeFilter(data6.startTime)\n\nunion all\nSelect\n    table_name as TableName,\n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_dev' AND TABLE_NAME='cdr_voice_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_dev`.`cdr_voice_details` \nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details' ORDER BY id DESC LIMIT 1 )\nas data7\nwhere data7.Notification=1 and data7.startTime IS Not Null and $__timeFilter(data7.startTime) ;\n"
    }
   ]
  },
  {
   "title": "Partitioning Threshold Not Reached Data",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "Select\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND TABLE_NAME='rule_engine_auditlog' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `$DB_stc_cdr_data`.`rule_engine_auditlog` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime \nFROM table_partition_policy WHERE table_name='rule_engine_auditlog' ORDER BY id DESC LIMIT 1 )\nas data1\nwhere data1.Notification=1 and data1.startTime IS Not Null\nand $__timeFilter(data1.startTime) \n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_daily' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_daily` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_daily' ORDER BY id DESC LIMIT 1 )\nas data8\nwhere data8.Notification=1 and data8.startTime IS Not Null\nand $__timeFilter(data8.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_hourly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_hourly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_hourly' ORDER BY id DESC LIMIT 1 )\nas data9\nwhere data9.Notification=1 and data9.startTime IS Not Null and $__timeFilter(data9.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_monthly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_monthly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_monthly' ORDER BY id DESC LIMIT 1 )\nas data10\nwhere data10.Notification=1 and data10.startTime IS Not Null and $__timeFilter(data10.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_weekly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_weekly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_data_details_weekly' ORDER BY id DESC LIMIT 1 )\nas data11\nwhere data11.Notification=1 and data11.startTime IS Not Null and $__timeFilter(data11.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < (YEAR(NOW())-IFNULL((select PARTITION_DESCRIPTION from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_data_details_yearly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_yearly` \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_data_details_yearly' ORDER BY id DESC LIMIT 1 )\nas data12\nwhere data12.Notification=1 and data12.startTime IS Not Null and $__timeFilter(data12.startTime)\n\nunion all\n-- Select\n-- \tUNIX_TIMESTAMP(startTime) as time,\n-- \tNotification, \n-- \ttable_name as TableName\n-- from\n-- (SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA=`$DB_stc_cdr_data` AND  TABLE_NAME='cdr_sms_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n-- ,(select FINAL_TIME from cdr_database.cdr_sms_details \n-- ORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\n-- FROM table_partition_policy WHERE table_name='cdr_sms_details' ORDER BY id DESC LIMIT 1 )\n-- as data13\n-- where data13.Notification=1 and data13.startTime IS Not Null and $__timeFilter(data13.startTime)\n\n-- union all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_daily' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_daily` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_sms_details_daily' ORDER BY id DESC LIMIT 1 )\nas data14\nwhere data14.Notification=1 and data14.startTime IS Not Null and $__timeFilter(data14.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_hourly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_hourly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_sms_details_hourly' ORDER BY id DESC LIMIT 1 )\nas data15\nwhere data15.Notification=1 and data15.startTime IS Not Null and $__timeFilter(data15.startTime)\n\nunion all\n\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_monthly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_monthly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details_monthly' ORDER BY id DESC LIMIT 1 )\nas data16\nwhere data16.Notification=1 and data16.startTime IS Not Null and $__timeFilter(data16.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_weekly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_weekly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details_weekly' ORDER BY id DESC LIMIT 1 )\nas data17\nwhere data17.Notification=1 and data17.startTime IS Not Null and $__timeFilter(data17.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < (YEAR(NOW())-IFNULL((select PARTITION_DESCRIPTION from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_sms_details_yearly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_yearly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details_yearly' ORDER BY id DESC LIMIT 1 )\nas data18\nwhere data18.Notification=1 and data18.startTime IS Not Null and $__timeFilter(data18.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_daily' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_daily`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_daily' ORDER BY id DESC LIMIT 1 )\nas data19\nwhere data19.Notification=1 and data19.startTime IS Not Null and $__timeFilter(data19.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_hourly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_hourly` \nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_hourly' ORDER BY id DESC LIMIT 1 )\nas data20\nwhere data20.Notification=1 and data20.startTime IS Not Null and $__timeFilter(data20.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_monthly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_monthly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_monthly' ORDER BY id DESC LIMIT 1 )\nas data21\nwhere data21.Notification=1 and data21.startTime IS Not Null and $__timeFilter(data21.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_weekly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_weekly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details_weekly' ORDER BY id DESC LIMIT 1 )\nas data22\nwhere data22.Notification=1 and data22.startTime IS Not Null and $__timeFilter(data22.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < (YEAR(NOW())-IFNULL((select PARTITION_DESCRIPTION from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='cdr_voice_details_yearly' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_yearly` \nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_voice_details_yearly' ORDER BY id DESC LIMIT 1 )\nas data23\nwhere data23.Notification=1 and data23.startTime IS Not Null and $__timeFilter(data23.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_cdr_data' AND  TABLE_NAME='rule_engine_alert_history' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select occurence_time from `$DB_stc_cdr_data`.`rule_engine_alert_history` \nORDER BY occurence_time DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='rule_engine_alert_history' ORDER BY id DESC LIMIT 1 )\nas data24\nwhere data24.Notification=1 and data24.startTime IS Not Null and $__timeFilter(data24.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_dev' AND  TABLE_NAME='auditlog_end_points' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `$DB_stc_dev`.`auditlog_end_points` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='auditlog_end_points' ORDER BY id DESC LIMIT 1 )\nas data4\nwhere data4.Notification=1 and data4.startTime IS Not Null and $__timeFilter(data4.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from   INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_dev' AND  TABLE_NAME='auditlog' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `$DB_stc_dev`.`auditlog` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='auditlog' ORDER BY id DESC LIMIT 1 )\nas data2\nwhere data2.Notification=1 and data2.startTime IS Not Null and $__timeFilter(data2.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_dev' AND TABLE_NAME='auditlog_api_transaction' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select CREATE_DATE from `$DB_stc_dev`.`auditlog_api_transaction` \nORDER BY CREATE_DATE DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='auditlog_api_transaction' ORDER BY id DESC LIMIT 1 )\nas data3\nwhere data3.Notification=1 and data3.startTime IS Not Null and $__timeFilter(data3.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_SCHEMA='$DB_stc_dev' AND  TABLE_NAME='cdr_sms_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select FINAL_TIME from `$DB_stc_dev`.`cdr_sms_details` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime\n\nFROM table_partition_policy WHERE table_name='cdr_sms_details' ORDER BY id DESC LIMIT 1 )\nas data5\nwhere data5.Notification=1 and data5.startTime IS Not Null and $__timeFilter(data5.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_SCHEMA='$DB_stc_dev' AND  TABLE_NAME='cdr_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select startTime from `$DB_stc_dev`.`cdr_details`  \nORDER BY startTime DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_details' ORDER BY id DESC LIMIT 1 )\nas data6\nwhere data6.Notification=1 and data6.startTime IS Not Null and $__timeFilter(data6.startTime)\n\nunion all\nSelect\n\tdatabase_name,\n    table_name as TableName,\n\tUNIX_TIMESTAMP(startTime) as time,\n\tNotification, \n    in_no_of_partitions\nfrom\n(SELECT CASE WHEN in_no_of_partitions < DATEDIFF(NOW(),IFNULL((select FROM_DAYS(PARTITION_DESCRIPTION) from  INFORMATION_SCHEMA.PARTITIONS WHERE  TABLE_SCHEMA='$DB_stc_dev' AND TABLE_NAME='cdr_voice_details' ORDER BY FROM_DAYS(PARTITION_DESCRIPTION) DESC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,in_no_of_partitions \n,(select ANSWERING_TIME from `$DB_stc_dev`.`cdr_voice_details` \nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM table_partition_policy WHERE table_name='cdr_voice_details' ORDER BY id DESC LIMIT 1 )\nas data7\nwhere data7.Notification=1 and data7.startTime IS Not Null and $__timeFilter(data7.startTime) ;\n"
    }
   ]
  }
 ]
}