{
 "title": "Purging Observing",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB_stc_dev", "query": "stc_dev" },
   { "name": "DB_stc_cdr_data", "query": "stc_cdr_data" }
  ]
 },
 "panels": [
  {
   "title": "Purging Threshold Reached",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_yearly` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_yearly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as sTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_yearly' ORDER BY id  DESC LIMIT 1)\n as data16\nwhere data16.Notification=0 and data16.sTime IS Not Null and $__timeFilter(data16.sTime) \n\nunion all\n\nselect  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_daily` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_daily`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as sTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_daily' ORDER BY id  DESC LIMIT 1)\nas data14\nwhere data14.Notification=0 and data14.sTime IS Not Null and $__timeFilter(data14.sTime) \nunion all\n\nselect  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_weekly` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_weekly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as sTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_weekly' ORDER BY id  DESC LIMIT 1)\nas data15\nwhere data15.Notification=0 and data15.sTime IS Not Null and $__timeFilter(data15.sTime) \n\nunion all\n\nselect  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_hourly` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `stc_cdr_data`.`cdr_voice_details_hourly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as sTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_hourly' ORDER BY id  DESC LIMIT 1)\nas data13\nwhere data13.Notification=0 and data13.sTime IS Not Null and $__timeFilter(data13.sTime) \n\nunion all\n\nselect  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `stc_dev`.`cdr_voice_details` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `stc_dev`.`cdr_voice_details`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as sTime \nFROM data_retention_purging WHERE table_name='cdr_voice_details' ORDER BY id  DESC LIMIT 1)\nas data12\nwhere data12.Notification=0 and data12.sTime IS Not Null and $__timeFilter(data12.sTime) \n\nunion all\n\nselect  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_weekly` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_weekly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as sTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_weekly' ORDER BY id  DESC LIMIT 1)\nas data10\nwhere data10.Notification=0 and data10.sTime IS Not Null and $__timeFilter(data10.sTime) \n\nunion all\n\nselect  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_daily` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_daily` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as sTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_daily' ORDER BY id  DESC LIMIT 1)\nas data9\nwhere data9.Notification=0 and data9.sTime IS Not Null and $__timeFilter(data9.sTime) \n\nunion all\nselect  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_hourly` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_hourly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as sTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_hourly' ORDER BY id  DESC LIMIT 1)\nas data8\nwhere data8.Notification=0 and data8.sTime IS Not Null and $__timeFilter(data8.sTime) \n\nunion all\nselect  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `stc_dev`.`cdr_sms_details` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `stc_dev`.`cdr_sms_details` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as sTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details' ORDER BY id  DESC LIMIT 1)\nas data7\nwhere data7.Notification=0 and data7.sTime IS Not Null and $__timeFilter(data7.sTime)\n\nunion all\n\nselect  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `stc_cdr_data`.`cdr_data_details_weekly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `stc_cdr_data`.`cdr_data_details_weekly` \nORDER BY startTime DESC LIMIT 1 ) as sTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_weekly' ORDER BY id  DESC LIMIT 1)\nas data5\nwhere data5.Notification=0 and data5.sTime IS Not Null and $__timeFilter(data5.sTime)\n\nunion all\nselect  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n  (SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `stc_cdr_data`.`cdr_data_details_hourly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `stc_cdr_data`.`cdr_data_details_hourly` \nORDER BY startTime DESC LIMIT 1 ) as sTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_hourly' ORDER BY id  DESC LIMIT 1)\nas data3\nwhere data3.Notification=0 and data3.sTime IS Not Null and $__timeFilter(data3.sTime) \n\nunion all\nselect  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `stc_dev`.`cdr_details` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days\n,(select startTime from `stc_dev`.`cdr_details` \nORDER BY startTime DESC LIMIT 1 ) as sTime \nFROM data_retention_purging WHERE table_name='cdr_details' ORDER BY id DESC LIMIT 1 )\nas data1\nwhere data1.Notification=0 and data1.sTime IS Not Null and $__timeFilter(data1.sTime) \n\nunion all\n\nselect \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `stc_cdr_data`.`cdr_data_details_daily` ORDER BY startTime ASC LIMIT 1 ),NOW())) THEN 1 ELSE 0 END AS Notification,database_name,table_name,days\n,(select startTime from `stc_cdr_data`.`cdr_data_details_daily` \nORDER BY startTime DESC LIMIT 1 ) as sTime \n FROM data_retention_purging WHERE table_name='cdr_data_details_daily' ORDER BY id  DESC LIMIT 1)\nas data2\nwhere data2.Notification=0 and data2.sTime IS Not Null and $__timeFilter(data2.sTime) \n\nunion all\nselect  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_yearly` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `stc_cdr_data`.`cdr_sms_details_yearly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as sTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_yearly' ORDER BY id  DESC LIMIT 1)\nas data11\nwhere data11.Notification=0 and data11.sTime IS Not Null and $__timeFilter(data11.sTime) \nunion all\nselect  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `stc_cdr_data`.`cdr_data_details_yearly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `stc_cdr_data`.`cdr_data_details_yearly` \nORDER BY startTime DESC LIMIT 1 ) as sTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_yearly' ORDER BY id  DESC LIMIT 1)\ndata6\nwhere data6.Notification=0 and data6.sTime IS Not Null and $__timeFilter(data6.sTime)\n\nunion all\n\nselect  \n  UNIX_TIMESTAMP(sTime) as time,\n  Notification,\n  table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `stc_cdr_data`.`cdr_data_details_monthly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `stc_cdr_data`.`cdr_data_details_monthly` \nORDER BY startTime DESC LIMIT 1 ) as sTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_monthly' ORDER BY id  DESC LIMIT 1)\nas data4\nwhere data4.Notification=0 and data4.sTime IS Not Null and $__timeFilter(data4.sTime)\n"
    }
   ]
  },
  {
   "title": "Purging Threshold Reached Data",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_dev`.`cdr_details` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days\n,(select startTime from `$DB_stc_dev`.`cdr_details` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_details' ORDER BY id DESC LIMIT 1 )\nas data1\nwhere data1.Notification=0 and $__timeFilter(data1.startTime) \n\nunion all\n\nselect \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_daily` ORDER BY startTime ASC LIMIT 1 ),NOW())) THEN 1 ELSE 0 END AS Notification,database_name,table_name,days\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_daily` \nORDER BY startTime DESC LIMIT 1 ) as startTime \n FROM data_retention_purging WHERE table_name='cdr_data_details_daily' ORDER BY id  DESC LIMIT 1)\nas data2\nwhere data2.Notification=0 and $__timeFilter(data2.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n  (SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_hourly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_hourly` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_hourly' ORDER BY id  DESC LIMIT 1)\nas data3\nwhere data3.Notification=0 and $__timeFilter(data3.startTime) \n\nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_monthly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_monthly` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_monthly' ORDER BY id  DESC LIMIT 1)\nas data4\nwhere data4.Notification=0 and $__timeFilter(data4.startTime)\nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_weekly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_weekly` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_weekly' ORDER BY id  DESC LIMIT 1)\nas data5\nwhere data5.Notification=0 and $__timeFilter(data5.startTime)\nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_yearly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_yearly` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_yearly' ORDER BY id  DESC LIMIT 1)\ndata6\nwhere data6.Notification=0 and $__timeFilter(data6.startTime)\n\n\nunion all\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_dev`.`cdr_sms_details` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_dev`.`cdr_sms_details` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details' ORDER BY id  DESC LIMIT 1)\nas data7\nwhere data7.Notification=0 and $__timeFilter(data7.startTime) \n\nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_hourly` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_hourly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_hourly' ORDER BY id  DESC LIMIT 1)\nas data8\nwhere data8.Notification=0 and $__timeFilter(data8.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_daily` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_daily` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_daily' ORDER BY id  DESC LIMIT 1)\nas data9\nwhere data9.Notification=0 and $__timeFilter(data9.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_weekly` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_weekly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_weekly' ORDER BY id  DESC LIMIT 1)\nas data10\nwhere data10.Notification=0 and $__timeFilter(data10.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_yearly` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_yearly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_yearly' ORDER BY id  DESC LIMIT 1)\nas data11\nwhere data11.Notification=0 and $__timeFilter(data11.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_dev`.`cdr_voice_details` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_dev`.`cdr_voice_details`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_voice_details' ORDER BY id  DESC LIMIT 1)\nas data12\nwhere data12.Notification=0 and $__timeFilter(data12.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_hourly` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_hourly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_hourly' ORDER BY id  DESC LIMIT 1)\nas data13\nwhere data13.Notification=0 and $__timeFilter(data13.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_daily` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_daily`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_daily' ORDER BY id  DESC LIMIT 1)\nas data14\nwhere data14.Notification=0 and $__timeFilter(data14.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_weekly` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_weekly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_weekly' ORDER BY id  DESC LIMIT 1)\nas data15\nwhere data15.Notification=0 and $__timeFilter(data15.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_yearly` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_yearly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_yearly' ORDER BY id  DESC LIMIT 1)\n as data16\n where data16.Notification=0 and $__timeFilter(data16.startTime) ;\n"
    }
   ]
  },
  {
   "title": "Purging Threshold Not Met",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n Notification,\n table_name as TableName\n \nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_dev`.`cdr_details` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days\n,(select startTime from `$DB_stc_dev`.`cdr_details` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_details' ORDER BY id DESC LIMIT 1 )\nas data1\nwhere data1.Notification=1 and $__timeFilter(data1.startTime) \n\nunion all\n\nselect \n Notification,\n table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_daily` ORDER BY startTime ASC LIMIT 1 ),NOW())) THEN 1 ELSE 0 END AS Notification,database_name,table_name,days\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_daily` \nORDER BY startTime DESC LIMIT 1 ) as startTime \n FROM data_retention_purging WHERE table_name='cdr_data_details_daily' ORDER BY id  DESC LIMIT 1)\nas data2\nwhere data2.Notification=1 and $__timeFilter(data2.startTime) \nunion all\n\nselect \n Notification,\n table_name as TableName\nfrom\n  (SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_hourly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_hourly` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_hourly' ORDER BY id  DESC LIMIT 1)\nas data3\nwhere data3.Notification=1 and $__timeFilter(data3.startTime) \n\nunion all\n\nselect \n Notification,\n table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_monthly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_monthly` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_monthly' ORDER BY id  DESC LIMIT 1)\nas data4\nwhere data4.Notification=1 and $__timeFilter(data4.startTime)\nunion all\n\nselect \n Notification,\n table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_weekly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_weekly` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_weekly' ORDER BY id  DESC LIMIT 1)\nas data5\nwhere data5.Notification=1 and $__timeFilter(data5.startTime)\nunion all\n\nselect \n Notification,\n table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_yearly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_yearly` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_yearly' ORDER BY id  DESC LIMIT 1)\ndata6\nwhere data6.Notification=1 and $__timeFilter(data6.startTime)\n\n\nunion all\nselect \n Notification,\n table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_dev`.`cdr_sms_details` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_dev`.`cdr_sms_details` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details' ORDER BY id  DESC LIMIT 1)\nas data7\nwhere data7.Notification=1 and $__timeFilter(data7.startTime) \n\nunion all\n\nselect \n Notification,\n table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_hourly` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_hourly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_hourly' ORDER BY id  DESC LIMIT 1)\nas data8\nwhere data8.Notification=1 and $__timeFilter(data8.startTime) \nunion all\n\nselect \n Notification,\n table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_daily` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_daily` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_daily' ORDER BY id  DESC LIMIT 1)\nas data9\nwhere data9.Notification=1 and $__timeFilter(data9.startTime) \nunion all\n\nselect \n Notification,\n table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_weekly` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_weekly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_weekly' ORDER BY id  DESC LIMIT 1)\nas data10\nwhere data10.Notification=1 and $__timeFilter(data10.startTime) \nunion all\n\nselect \n Notification,\n table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_yearly` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_yearly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_yearly' ORDER BY id  DESC LIMIT 1)\nas data11\nwhere data11.Notification=1 and $__timeFilter(data11.startTime) \nunion all\n\nselect \n Notification,\n table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_dev`.`cdr_voice_details` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_dev`.`cdr_voice_details`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_voice_details' ORDER BY id  DESC LIMIT 1)\nas data12\nwhere data12.Notification=1 and $__timeFilter(data12.startTime) \nunion all\n\nselect \n Notification,\n table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_hourly` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_hourly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_hourly' ORDER BY id  DESC LIMIT 1)\nas data13\nwhere data13.Notification=1 and $__timeFilter(data13.startTime) \nunion all\n\nselect \n Notification,\n table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_daily` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_daily`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_daily' ORDER BY id  DESC LIMIT 1)\nas data14\nwhere data14.Notification=1 and $__timeFilter(data14.startTime) \nunion all\n\nselect \n Notification,\n table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_weekly` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_weekly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_weekly' ORDER BY id  DESC LIMIT 1)\nas data15\nwhere data15.Notification=1 and $__timeFilter(data15.startTime) \nunion all\n\nselect \n Notification,\n table_name as TableName\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_yearly` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_yearly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_yearly' ORDER BY id  DESC LIMIT 1)\n as data16\n where data16.Notification=1 and $__timeFilter(data16.startTime) ;\n"
    }
   ]
  },
  {
   "title": "Purging Threshold Not Met Data",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "select\n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_dev`.`cdr_details` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days\n,(select startTime from `$DB_stc_dev`.`cdr_details` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_details' ORDER BY id DESC LIMIT 1 )\nas data1\nwhere data1.Notification=1 and $__timeFilter(data1.startTime) \n\nunion all\n\nselect \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_daily` ORDER BY startTime ASC LIMIT 1 ),NOW())) THEN 1 ELSE 0 END AS Notification,database_name,table_name,days\n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_daily` \nORDER BY startTime DESC LIMIT 1 ) as startTime \n FROM data_retention_purging WHERE table_name='cdr_data_details_daily' ORDER BY id  DESC LIMIT 1)\nas data2\nwhere data2.Notification=1 and $__timeFilter(data2.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n  (SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_hourly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_hourly` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_hourly' ORDER BY id  DESC LIMIT 1)\nas data3\nwhere data3.Notification=1 and $__timeFilter(data3.startTime) \n\nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_monthly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_monthly` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_monthly' ORDER BY id  DESC LIMIT 1)\nas data4\nwhere data4.Notification=1 and $__timeFilter(data4.startTime)\nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_weekly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_weekly` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_weekly' ORDER BY id  DESC LIMIT 1)\nas data5\nwhere data5.Notification=1 and $__timeFilter(data5.startTime)\nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select startTime from `$DB_stc_cdr_data`.`cdr_data_details_yearly` ORDER BY startTime ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select startTime from `$DB_stc_cdr_data`.`cdr_data_details_yearly` \nORDER BY startTime DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_data_details_yearly' ORDER BY id  DESC LIMIT 1)\ndata6\nwhere data6.Notification=1 and $__timeFilter(data6.startTime)\n\n\nunion all\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_dev`.`cdr_sms_details` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_dev`.`cdr_sms_details` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details' ORDER BY id  DESC LIMIT 1)\nas data7\nwhere data7.Notification=1 and $__timeFilter(data7.startTime) \n\nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_hourly` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_hourly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_hourly' ORDER BY id  DESC LIMIT 1)\nas data8\nwhere data8.Notification=1 and $__timeFilter(data8.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_daily` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_daily` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_daily' ORDER BY id  DESC LIMIT 1)\nas data9\nwhere data9.Notification=1 and $__timeFilter(data9.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_weekly` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_weekly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_weekly' ORDER BY id  DESC LIMIT 1)\nas data10\nwhere data10.Notification=1 and $__timeFilter(data10.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_yearly` ORDER BY FINAL_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select FINAL_TIME from `$DB_stc_cdr_data`.`cdr_sms_details_yearly` \nORDER BY FINAL_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_sms_details_yearly' ORDER BY id  DESC LIMIT 1)\nas data11\nwhere data11.Notification=1 and $__timeFilter(data11.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_dev`.`cdr_voice_details` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_dev`.`cdr_voice_details`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime \nFROM data_retention_purging WHERE table_name='cdr_voice_details' ORDER BY id  DESC LIMIT 1)\nas data12\nwhere data12.Notification=1 and $__timeFilter(data12.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_hourly` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_hourly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_hourly' ORDER BY id  DESC LIMIT 1)\nas data13\nwhere data13.Notification=1 and $__timeFilter(data13.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_daily` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_daily`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_daily' ORDER BY id  DESC LIMIT 1)\nas data14\nwhere data14.Notification=1 and $__timeFilter(data14.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_weekly` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_weekly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_weekly' ORDER BY id  DESC LIMIT 1)\nas data15\nwhere data15.Notification=1 and $__timeFilter(data15.startTime) \nunion all\n\nselect  \n  database_name,  \n  table_name as TableName,\n  UNIX_TIMESTAMP(startTime) as time,\n  Notification,\n  days\nfrom\n(SELECT CASE WHEN days < DATEDIFF(NOW(),IFNULL((select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_yearly` ORDER BY ANSWERING_TIME ASC  LIMIT 1 ),NOW())) THEN  1 ELSE 0 END AS Notification,database_name,table_name,days \n,(select ANSWERING_TIME from `$DB_stc_cdr_data`.`cdr_voice_details_yearly`\nORDER BY ANSWERING_TIME DESC LIMIT 1 ) as startTime\nFROM data_retention_purging WHERE table_name='cdr_voice_details_yearly' ORDER BY id  DESC LIMIT 1)\n as data16\n where data16.Notification=1 and $__timeFilter(data16.startTime) ;\n"
    }
   ]
  }
 ]
}