{
 "title": "Airflow Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Rule Engine Dags",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from dag_run as a \nINNER JOIN\nairflow_db.dag_tag as b \non a.dag_id = b.dag_id\nwhere b.name='Rule Trigger' and a.state='running';"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from dag_run as a \nINNER JOIN\nairflow_db.dag_tag as b \non a.dag_id = b.dag_id\nwhere b.name='Rule Trigger' and a.state='failed';"
    }
   ]
  },
  {
   "title": "Rule Engine Dags Current State",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "rawSql": "Select count(*) as value, state as state from dag_run as a \nINNER JOIN\nairflow_db.dag_tag as b \non a.dag_id = b.dag_id\nwhere b.name='Rule Trigger'\ngroup by state;"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from dag_run as a \nINNER JOIN\nairflow_db.dag_tag as b \non a.dag_id = b.dag_id\nwhere b.name='Rule Trigger' and a.state='success';"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from dag_run as a \nINNER JOIN\nairflow_db.dag_tag as b \non a.dag_id = b.dag_id\nwhere b.name='Rule Trigger' and a.state IN ('running', 'success', 'failed', 'running');"
    }
   ]
  },
  {
   "title": "Rule Trigger Dags",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select distinct(a.id), b.name, a.dag_id, a.state, f.task_id,\na.execution_date, a.start_date, a.run_id from dag_run as a \nINNER JOIN\nairflow_db.dag_tag as b \non a.dag_id = b.dag_id \nINNER JOIN\nairflow_db.task_fail as f\non b.dag_id = f.dag_id\nwhere b.name='Rule Trigger' and a.state='failed' ORDER BY a.id desc;"
    }
   ]
  },
  {
   "title": "Automation Dags",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from dag_run as a \nINNER JOIN\nairflow_db.dag_tag as b \non a.dag_id = b.dag_id\nwhere b.name='Automation' and a.state='running';"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from dag_run as a \nINNER JOIN\nairflow_db.dag_tag as b \non a.dag_id = b.dag_id\nwhere b.name='Automation' and a.state='failed';"
    }
   ]
  },
  {
   "title": "Automation Dags Current State",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 21 },
   "targets": [
    {
     "rawSql": "Select count(*) as value, state as state from dag_run as a \nINNER JOIN\nairflow_db.dag_tag as b \non a.dag_id = b.dag_id\nwhere b.name='Automation'\ngroup by state;"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from dag_run as a \nINNER JOIN\nairflow_db.dag_tag as b \non a.dag_id = b.dag_id\nwhere b.name='Automation' and a.state='success';"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from dag_run as a \nINNER JOIN\nairflow_db.dag_tag as b \non a.dag_id = b.dag_id\nwhere b.name='Automation' and a.state IN ('running', 'success', 'failed');"
    }
   ]
  },
  {
   "title": "Automation Dags",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "select distinct(a.id), b.name, a.dag_id, a.state, f.task_id,\na.execution_date, a.start_date, a.run_id from dag_run as a \nINNER JOIN\nairflow_db.dag_tag as b \non a.dag_id = b.dag_id \nINNER JOIN\nairflow_db.task_fail as f\non b.dag_id = f.dag_id\nwhere b.name='Automation' and a.state='failed' ORDER BY a.id desc;"
    }
   ]
  }
 ]
}