{
 "title": "AMX_Dashboard_CorrelatorID",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Success",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  count(is_successful) as counts, api.name as API\nFROM goup_cmpamx_interface_testing_db.audit_log \nleft join api on api.id = audit_log.api_id\nwhere   $__unixEpochFilter(log_time) and\nis_successful=1 and api.name Is NOT NULL\ngroup by API\norder by counts desc;"
    }
   ]
  },
  {
   "title": "Failure",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  count(is_successful) as counts, api.name as API\nFROM goup_cmpamx_interface_testing_db.audit_log \nleft join api on api.id = audit_log.api_id\nwhere   $__unixEpochFilter(log_time) and\nis_successful=0 and api.name Is NOT NULL\ngroup by API\norder by counts desc;"
    }
   ]
  },
  {
   "title": "Correlator",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT distinct(tracking_message_header) as \"TransanctionID\",\napi.name as \"API\", api.alias as \"API Alias\",audit_log.is_successful as \"Is Successful\",\n\nif(value like \"%responseDescription%\",\n substring_index(substring_index(value,'RequestBody:',-1),\",\",1),\n substring_index(substring_index(value,'correlatorId:',-1),\",\",1))  as \"RequestCorrelatorId\",  \nSUBSTRING(if(value like \"%responseDescription%\",\n substring_index(substring_index(value,'Response Message: ',-2),\",\",1),\n substring_index(substring_index(value,'correlatorId:',-2),\",\",1)),1, LENGTH(if(value like \"%responseDescription%\",\n substring_index(substring_index(value,'Response Message: ',-2),\",\",1),\n substring_index(substring_index(value,'correlatorId:',-2),\",\",1)))-4) as \"ResponseCorrelatorId\",\n\n\naudit_log.message as \"Message\",\naudit_log.value as \"Value\",\n\nfrom_unixtime(log_time) as \"Timestamp\"\n\nFROM audit_log\nleft join api\non api.id = api_id\nwhere $__unixEpochFilter(log_time) and\nvalue like '%correlatorId:%'  and api.name Is NOT NULL\n;"
    }
   ]
  }
 ]
}