{
 "title": "Order Expired Notification",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "UAE Order Expired Success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(b.imsi) from\n(select log_id, \nfrom_unixtime(log_time) as log_time,\nlog_description from gmonstar_notification_engine_1_8.notification_audit_log\n where is_successful = 1\n and log_description like \"%orderExpired%\"  -- orderExpired\nand log_id in (select log_id \n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = \"OrderExpired\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect log_id, d.imsi from \n(\nselect log_id , substring_index(substring_index(value,'|#@|',-4),'|#@|',1) as imsi\n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = \"OrderExpired\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi like '42402%')b\nON a.log_id = b.log_id\n"
    }
   ]
  },
  {
   "title": "UAE Order Expired Failure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(b.imsi) from\n(select log_id, \nfrom_unixtime(log_time) as log_time,\nlog_description from gmonstar_notification_engine_1_8.notification_audit_log\n where is_successful = 0\n and log_description like \"%orderExpired%\"\n-- and value like \"%OrderExpired%\"  -- orderExpired\nand log_id in (select log_id \n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n\n(\nselect log_id, d.imsi from \n(\nselect log_id , substring_index(substring_index(value,'|#@|',-4),'|#@|',1) as imsi\n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi like '42402%')b\nON a.log_id = b.log_id"
    }
   ]
  },
  {
   "title": "UAE Order Expired Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(b.imsi) from\n(\nselect log_id, \nfrom_unixtime(log_time) as log_time,\nlog_description from gmonstar_notification_engine_1_8.notification_audit_log\n where is_successful IN (1, 0)\n and log_description like \"%orderExpired%\"  -- orderExpired\nand log_id in \n(\nselect log_id \n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = \"OrderExpired\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect log_id, d.imsi from \n(\nselect log_id , substring_index(substring_index(value,'|#@|',-4),'|#@|',1) as imsi\n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = \"OrderExpired\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi like '42402%')b\nON a.log_id = b.log_id\n"
    }
   ]
  },
  {
   "title": "Kuwait Order Expired Success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(b.imsi) from\n(select log_id, \nfrom_unixtime(log_time) as log_time,\nlog_description from gmonstar_notification_engine_1_8.notification_audit_log\n where is_successful = 1\n and log_description like \"%orderExpired%\"  -- orderExpired\nand log_id in (select log_id \n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect log_id, d.imsi from \n(\nselect log_id , substring_index(substring_index(value,'|#@|',-4),'|#@|',1) as imsi\n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi like '41904%')b\nON a.log_id = b.log_id\n"
    }
   ]
  },
  {
   "title": "Kuwait Order Expired Failure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(b.imsi) from\n(select log_id, \nfrom_unixtime(log_time) as log_time,\nlog_description from gmonstar_notification_engine_1_8.notification_audit_log\n where is_successful = 0\n and log_description like \"%orderExpired%\"\n-- and value like \"%OrderExpired%\"  -- orderExpired\nand log_id in (select log_id \n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n\n(\nselect log_id, d.imsi from \n(\nselect log_id , substring_index(substring_index(value,'|#@|',-4),'|#@|',1) as imsi\n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi like '41904%')b\nON a.log_id = b.log_id"
    }
   ]
  },
  {
   "title": "Kuwait Order Expired Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(b.imsi) from\n(select log_id, \nfrom_unixtime(log_time) as log_time,\nlog_description from gmonstar_notification_engine_1_8.notification_audit_log\n where is_successful IN (1,0)\n and log_description like \"%orderExpired%\"  -- orderExpired\nand log_id in (select log_id \n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect log_id, d.imsi from \n(\nselect log_id , substring_index(substring_index(value,'|#@|',-4),'|#@|',1) as imsi\n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi like '41904%')b\nON a.log_id = b.log_id\n"
    }
   ]
  },
  {
   "title": "UAE Order Expired Error",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select \"OrderExpired\" as \"API\", a.*, b.imsi from\n(select log_id,\nfrom_unixtime(log_time) as log_time,\nlog_description from gmonstar_notification_engine_1_8.notification_audit_log\n where is_successful = 0\n and log_description like '%orderExpired%'\n-- and value like \"%OrderExpired%\"  -- orderExpired\nand log_id in (select log_id \n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect log_id, d.imsi from \n(\nselect log_id , substring_index(substring_index(value,'|#@|',-4),'|#@|',1) as imsi\n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi like '42402%')b\nON a.log_id = b.log_id"
    }
   ]
  },
  {
   "title": "Kuwait Order Expired Error",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "select \"OrderExpired\" as \"API\", a.*, b.imsi from\n(select log_id, \nfrom_unixtime(log_time) as log_time,\nlog_description from gmonstar_notification_engine_1_8.notification_audit_log\n where is_successful = 0\n and log_description like '%orderExpired%'\n-- and value like \"%OrderExpired%\"  -- orderExpired\nand log_id in (select log_id \n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect log_id, d.imsi from \n(\nselect log_id , substring_index(substring_index(value,'|#@|',-4),'|#@|',1) as imsi\n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi like '41904%')b\nON a.log_id = b.log_id"
    }
   ]
  },
  {
   "title": "UAE Order Expired Success",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select \"OrderExpired\" as \"API\", a.*, b.imsi from\n(select log_id, \nfrom_unixtime(log_time) as log_time,\nlog_description from gmonstar_notification_engine_1_8.notification_audit_log\n where is_successful = 1\nand log_description like \"%orderExpired%\"  -- orderExpired\nand log_id in (select log_id \n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n\n(\nselect log_id, d.imsi from \n(\nselect log_id , substring_index(substring_index(value,'|#@|',-4),'|#@|',1) as imsi\n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi like '42402%')b\nON a.log_id = b.log_id\n"
    }
   ]
  },
  {
   "title": "Kuwait Order Expired Success",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "select \"OrderExpired\" as \"API\", a.*, b.imsi from\n(select log_id, \nfrom_unixtime(log_time) as log_time,\nlog_description from gmonstar_notification_engine_1_8.notification_audit_log\n where is_successful = 1\nand log_description like \"%orderExpired%\"  -- orderExpired\nand log_id in (select log_id \n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n\n(\nselect log_id, d.imsi from \n(\nselect log_id , substring_index(substring_index(value,'|#@|',-4),'|#@|',1) as imsi\n from gmonstar_notification_engine_1_8.notification_audit_log where parent_api_name = 'OrderExpired'\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi like '41904%')b\nON a.log_id = b.log_id\n"
    }
   ]
  }
 ]
}