{
 "title": "profileSwitch Notification",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "UAE Profile Switch Begun Success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(distinct a.tracking_message_header) from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nmessage from gmonstar_orchestration_1_8.audit_log\n where is_successful = 1\n and message  like \"%/profileSwitch%\" \n and value like \"%profileSwitchState:Begun%\"\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"AE\")b\nON a.tracking_message_header = b.tracking_message_header"
    }
   ]
  },
  {
   "title": "UAE Profile Switch Begun Failure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(distinct a.tracking_message_header) from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nvalue,\nmessage from gmonstar_orchestration_1_8.audit_log\n where is_successful = 0 and\n message like \"%/profileSwitch%\"\n and value like \"%profileSwitchState:Begun%\"\n-- orderExpired\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header, d.imsi from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"AE\")b\nON a.tracking_message_header = b.tracking_message_header"
    }
   ]
  },
  {
   "title": "UAE Profile Switch Begun Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(distinct a.tracking_message_header) from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nmessage from gmonstar_orchestration_1_8.audit_log\nwhere \n  message like \"%/profileSwitch%\"\n  and value like \"%profileSwitchState:Begun%\"\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header, d.imsi from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"AE\")b\nON a.tracking_message_header = b.tracking_message_header\n"
    },
    {
     "rawSql": "select  count(distinct a.tracking_message_header) from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nmessage from gmonstar_orchestration_1_8.audit_log\nwhere \n  is_successful IN (1,0)\n and message  like \"%/profileSwitch%\" \n and value like \"%profileSwitchState:Completed%\"\n\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header, d.imsi from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"AE\")b\nON a.tracking_message_header = b.tracking_message_header\n"
    }
   ]
  },
  {
   "title": "Kuwait Profile Switch Begun Success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(distinct a.tracking_message_header) from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nmessage from gmonstar_orchestration_1_8.audit_log\n where is_successful = 1\n \n and value like \"%profileSwitchState:Begun%\"\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"KW\")b\nON a.tracking_message_header = b.tracking_message_header"
    }
   ]
  },
  {
   "title": "Kuwait Profile Switch Begun failure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(distinct a.tracking_message_header) from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nmessage from gmonstar_orchestration_1_8.audit_log\n where is_successful = 0\n\n and value like \"%profileSwitchState:Begun%\"\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"KW\")b\nON a.tracking_message_header = b.tracking_message_header\n"
    }
   ]
  },
  {
   "title": "Kuwait Profile Switch Begun Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(distinct a.tracking_message_header) from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nmessage from gmonstar_orchestration_1_8.audit_log\nwhere\n-- is_successful IN (0, 1) and\n   message like \"%/profileSwitch%\"\n   and value like \"%profileSwitchState:Begun%\"\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header, d.imsi from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"KW\")b\nON a.tracking_message_header = b.tracking_message_header\n"
    }
   ]
  },
  {
   "title": "UAE Profile Switch Complete Success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(distinct a.tracking_message_header) from\n(\nselect distinct tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nmessage from gmonstar_orchestration_1_8.audit_log\n where is_successful = 1\n and message  like \"%/profileSwitch%\" \n and value like \"%profileSwitchState:Completed%\"\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"AE\")b\nON a.tracking_message_header = b.tracking_message_header"
    }
   ]
  },
  {
   "title": "UAE Profile Switch Complete Failure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(distinct a.tracking_message_header) from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nvalue,\nmessage from gmonstar_orchestration_1_8.audit_log\n where is_successful = 0 and\nmessage like \"%/profileSwitch%\"\n and value like \"%profileSwitchState:Complete%\"\n-- orderExpired\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header, d.imsi from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"AE\")b\nON a.tracking_message_header = b.tracking_message_header"
    }
   ]
  },
  {
   "title": "UAE Profile Switch Completed Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(distinct a.tracking_message_header) from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nmessage from gmonstar_orchestration_1_8.audit_log\n where -- is_successful IN (1, 0) and\n  message like \"%/profileSwitch%\" -- orderExpired\n  and value like \"%profileSwitchState:Completed%\"\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header, d.imsi from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"AE\")b\nON a.tracking_message_header = b.tracking_message_header\n"
    }
   ]
  },
  {
   "title": "Kuwait Profile Switch Completed Success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(distinct a.tracking_message_header) from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nmessage from gmonstar_orchestration_1_8.audit_log\n where is_successful = 1\n and message  like \"%Notification Sent Successfully Toward GM. [/profileSwitch]%\" \n and value like \"%profileSwitchState:Completed%\"\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"KW\")b\nON a.tracking_message_header = b.tracking_message_header"
    }
   ]
  },
  {
   "title": "Kuwait Profile Switch Complete failure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(distinct a.tracking_message_header) from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nvalue,\nmessage from gmonstar_orchestration_1_8.audit_log\n where is_successful = 0 and\nmessage like \"%/profileSwitch%\"\n and value like \"%profileSwitchState:Completed%\"\n-- orderExpired\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header, d.imsi from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"KW\")b\nON a.tracking_message_header = b.tracking_message_header"
    }
   ]
  },
  {
   "title": "Kuwait Profile Switch Complete Total ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select  count(distinct a.tracking_message_header) from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nmessage from gmonstar_orchestration_1_8.audit_log\n where \n-- is_successful IN (1, 0) and\n  message like \"%/profileSwitch%\"\n   and value like \"%profileSwitchState:Completed%\"\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header, d.imsi from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"KW\")b\nON a.tracking_message_header = b.tracking_message_header\n"
    }
   ]
  },
  {
   "title": "UAE Profile Switch Error",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select   a.* from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nsubstring_index(substring_index(value,\"profileSwitchState:\",-1),\",\",1) as \"ProfileSwitchState\",\nsubstring_index(substring_index(message,\"Imsi is:[\",-1),\"]\",1) as \"IMSI\",\nmessage as \"Message\"\n\nfrom gmonstar_orchestration_1_8.audit_log\n where is_successful = 0 and\nmessage like \"%/profileSwitch%\" -- orderExpired\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header, d.imsi from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"AE\")b\nON a.tracking_message_header = b.tracking_message_header\n-- group by a.tracking_message_header "
    }
   ]
  },
  {
   "title": "Kuwait Profile Switch Error",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select   a.* from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as log_time,\nsubstring_index(substring_index(value,\"profileSwitchState:\",-1),\",\",1) as \"ProfileSwitchState\",\nsubstring_index(substring_index(message,\"Imsi is:[\",-1),\"]\",1) as \"IMSI\",\nmessage as \"Message\"\nfrom gmonstar_orchestration_1_8.audit_log\n where is_successful = 0 and\nmessage like \"%/profileSwitch%\" -- orderExpired\nand tracking_message_header in \n(\nselect tracking_message_header\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header, d.imsi from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"KW\")b\nON a.tracking_message_header = b.tracking_message_header\n-- group by a.tracking_message_header "
    }
   ]
  },
  {
   "title": "UAE Profiile Switch Success",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "select   a.* from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as \"LogTime\",\nsubstring_index(substring_index(value,\"profileSwitchState:\",-1),\",\",1) as \"ProfileSwitchState\",\nsubstring_index(substring_index(message,\"Imsi is:[\",-1),\"]\",1) as \"IMSI\",\nmessage as \"Message\"\nfrom gmonstar_orchestration_1_8.audit_log\n where is_successful = 1 and\nmessage like \"%/profileSwitch%\" -- orderExpired\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header, d.imsi from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"AE\")b\nON a.tracking_message_header = b.tracking_message_header\n-- group by a.tracking_message_header "
    }
   ]
  },
  {
   "title": "Kuwait Profile Switch Success",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "select   a.* from\n(\nselect tracking_message_header, \nfrom_unixtime(log_time) as \"LogTime\",\nsubstring_index(substring_index(value,\"profileSwitchState:\",-1),\",\",1) as \"ProfileSwitchState\",\nsubstring_index(substring_index(message,\"Imsi is:[\",-1),\"]\",1) as \"IMSI\",\nmessage as \"Message\"\nfrom gmonstar_orchestration_1_8.audit_log\n where is_successful = 1 and\nmessage like \"%/profileSwitch%\" -- orderExpired\nand tracking_message_header in \n(\nselect tracking_message_header \n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and  $__unixEpochFilter(log_time)))a\n \ninner join\n(\nselect tracking_message_header, d.imsi from \n(\nselect tracking_message_header , substring_index(substring_index(value,'|#@|',1),'|#@|',1) as imsi\n from gmonstar_orchestration_1_8.audit_log where parent_api_name = \"UpdateSimProfile\"\n and   $__unixEpochFilter(log_time) )d\nwhere d.imsi = \"KW\")b\nON a.tracking_message_header = b.tracking_message_header\n-- group by a.tracking_message_header "
    }
   ]
  }
 ]
}